Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    patience: 3
    save_best_only: True
    eval_interval_epochs: 1
    debug_mode: False

SimpleX_yelp18_m1:
    model: SimpleX
    dataset_id: yelp18_m1_9217a019
    metrics: ['Recall(k=20)', 'Recall(k=50)', 'NDCG(k=20)', 'NDCG(k=50)', 'HitRate(k=20)', 'HitRate(k=50)']
    optimizer: adam
    learning_rate: 1.e-4
    batch_size: 512
    num_negs: 1000
    embedding_dim: 64
    aggregator: mean
    gamma: 1
    user_id_field: user_id
    item_id_field: item_id
    user_history_field: user_history
    embedding_regularizer: 1.e-8
    net_regularizer: 0
    net_dropout: 0.1
    attention_dropout: 0
    enable_bias: False
    similarity_score: cosine
    loss: CosineContrastiveLoss
    margin: 0.9
    negative_weight: 150
    sampling_num_process: 1
    fix_sampling_seeds: False
    ignore_pos_items: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: 'Recall(k=20)'
    monitor_mode: 'max'
    